function Jexpr = dqwq_dxi(in1,in2,in3)
%DQWQ_DXI
%    JEXPR = DQWQ_DXI(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    24-Sep-2018 16:31:50

q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
w1 = in3(1,:);
w2 = in3(2,:);
w3 = in3(3,:);
xi1 = in1(1,:);
xi2 = in1(2,:);
xi3 = in1(3,:);
t2 = exp(xi2);
t3 = exp(-xi3);
t4 = q2.*t3;
t5 = q3.*t2;
t6 = q1+t4+t5;
t7 = exp(-xi1);
t8 = exp(-xi2);
t9 = exp(xi1);
t10 = exp(xi3);
t11 = t6.*w1;
t12 = q3.*t7;
t13 = q1.*t10;
t14 = q2+t12+t13;
t15 = t14.*w2;
t16 = q1.*t8;
t17 = q2.*t9;
t18 = q3+t16+t17;
t19 = t18.*w3;
t20 = t11+t15+t19;
t21 = q3.*t7.*w2;
t27 = q2.*t9.*w3;
t22 = t21-t27;
t23 = q3.*t2.*w1;
t28 = q1.*t8.*w3;
t24 = t23-t28;
t25 = q2.*t3.*w1;
t29 = q1.*t10.*w2;
t26 = t25-t29;
Jexpr = reshape([-t6.*t22,-t14.*t22-q3.*t7.*t20,-t18.*t22+q2.*t9.*t20,t6.*t24+q3.*t2.*t20,t14.*t24,t18.*t24-q1.*t8.*t20,-t6.*t26-q2.*t3.*t20,-t14.*t26+q1.*t10.*t20,-t18.*t26],[3,3]);
